# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  code:
    docker:
    - image: circleci/php:7.2-fpm-node-browsers

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-

    - run: composer install -n -q -o
    - run: yarn

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    - run: composer run test

    # remove dev packages
    - run: composer install -o -n -q --prefer-dist --no-dev

    - run:
        name: deploy
        command: |
          export DEPLOY_USERNAME=investprev
          if [[ "${CIRCLE_BRANCH}" = 'master' ]]; then DEPLOY_USERNAME=invest; fi
          mkdir ~/.ssh || rm -f ~/.ssh/known_hosts
          mv ./.circleci/known_hosts ~/.ssh/
          rsync -rptgoDzL --delete src www cli-config.php composer.* ${DEPLOY_USERNAME}@nbf01.opsserver.ch:.
          rsync -rptgoDzL cnf ${DEPLOY_USERNAME}@nbf01.opsserver.ch:.
          ssh ${DEPLOY_USERNAME}@nbf01.opsserver.ch "source .zshrc;
          source .profile;
          composer install --no-dev -o &&
          vendor/bin/doctrine orm:schema-tool:update --force &&
          vendor/bin/doctrine orm:generate-proxies -q /home/${DEPLOY_USERNAME}/tmp"
          sleep 5
          ssh ${DEPLOY_USERNAME}@nbf01.opsserver.ch "sudo /usr/sbin/service php72-fpm reload"


workflows:
  version: 2
  build:
    jobs:
    - code:
        filters:
          branches:
            only:
            - master
            - development
