<!DOCTYPE html>
<html class="helio login-pf" lang="en">
<?php \Helio\Invest\Helper\ViewHelper::includeShared('head'); ?>
<body>
<div id="notificationContainer"></div>
<div class="business-hero">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
                <header class="login-pf-page-header">
                    <img class="login-pf-brand" src="/images/logo.svg" alt=" logo"/>
                    <h2 class="display">
                        The Autonomous Cloud Computing Exchange
                    </h2>
                    <p>
                        <strong>Request Access</strong> This Website can only be viewd with a valid link.
                        If you have forgotten your link or you want to request access, please enter your E-Mail address
                        below.
                    </p>
                </header>
                <div>
                    <?php
                    /** @var Helio\Invest\Model\User $user */
                    if (isset($user) && $user->getId()) {
                        echo '<div>';
                        if ($user->isActive()) {
                            echo <<<EOSM
                    Thank you for signing in.<br />
                    You have received an E-Mail to the submitted address containing your login link.<br/>
EOSM;
                        } else {
                            echo <<<EORM
                    Thank you for your registration.<br />
                    We will review your request and send you an invitation link soon.<br/>
EORM;
                        }
                        echo '</div>';
                    } else {
                        if (isset($loggedOut)) {

                            echo <<<EOLO
                            <header class="login-pf-header">
                                <h2>Logged out!</h2>
                            </header>
                                <div>Thank you, come again.</div>'
EOLO;
                        } else {
                            echo <<<EOF
                            <header class="login-pf-header">
                                <h3 style="color: white;">Request Access</h3>
                            </header>
                            <form id="register" action="user/login" method="POST">
                                <div class="form-group" style="color:white;">
                                    <label class="sr-only" for="exampleInputEmail1">What is your Email address?</label>
                                    <input type="email" class="form-control  input-lg" id="email" name="email"
                                           placeholder="Email address">
                                    <br/>
                                    <small>
                                        Please use an email address that you have always access to,
                                        since we currently only support password-less login via magic link.
                                    </small>
                                    <br/>
                                    <strong>
                                        We'll never share your email address with anyone.
                                    </strong>
                                </div>
                                <button type="submit" class="btn-pill btn-pill-primary btn-pill-lg">Log In / Sign Up</button>
                            </form>
EOF;
                        }
                    }
                    ?>
                    <br/>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
