<!DOCTYPE html>
<html class="helio login" lang="en">
<?php \Helio\Invest\Helper\ViewHelper::includeShared('head'); ?>
<body>
<div id="notificationContainer"></div>
<div class="business-hero">
    <div class="container">
        <header>
            <img src="/images/logo.svg" alt=" logo"/>
            <h2 class="display">
                The Autonomous Cloud Computing Exchange
            </h2>
        </header>
        <div class="row">
            <?php
            /** @var Helio\Invest\Model\User $user */
            if (isset($user) && $user->getId()) {
                echo '<div class="col">';
                if ($user->isActive()) {
                    echo <<<EOSM
                    <p>
                        <strong>Thank you for signing in.</strong><br />
                        You have received an E-Mail to the submitted address containing your login link.<br/>
                    </p>
EOSM;
                } else {
                    echo <<<EORM
                    <p>
                        <strong>Thank you for your registration.</strong><br />
                        We will review your request and send you an invitation link soon.<br/>
                    </p>
EORM;
                }
                echo '</div>';
            } else {
                if (isset($loggedOut)) {

                    echo <<<EOLO
                            <header>
                                <h2>Logged out!</h2>
                            </header>
                                <div>Thank you, come again.</div>'
EOLO;
                } else {
                    echo <<<EOF
                        <div class="col">
                            <header>
                                <br /><br />
                                <h3 style="color: white;">Request Access</h3>        
                            </header>
                            <p>
                                This Website can only be viewed with a valid link.
                                If you have forgotten your link or you want to request access,
                                please enter your E-Mail address below.

                                Please use an email address that you have always access to,
                                since we currently only support password-less login via magic link.
                                <br/>
                                <strong>
                                    We'll never share your email address with anyone.
                                </strong>
                            </p>
                            </div>
                            </div>
                            <div class="row">
                            <div class="col-lg-6">
                            <form id="register" action="user/login" method="POST">
                                <div class="form-group">
                                    <label class="sr-only" for="email">What is your Email address?</label>
                                    <input type="email" class="form-control  input-lg" id="email" name="email"
                                           placeholder="Email address">
                                </div>
                                <button type="submit" class="btn-pill btn-pill-primary btn-pill-lg">Log In / Sign Up</button>
                            </form>
                            </div>
EOF;
                }
            }
            ?>
            <br/>
        </div>
    </div>
</div>
</body>
</html>
