<!DOCTYPE html>
<html class="helio" lang="en">
<?php \Helio\Invest\Helper\ViewHelper::includeShared('head'); ?>
<body>
<div id="notificationContainer"></div>
<div class="business-hero">
    <div class="container">
        <h2>Status</h2>
        <p>
            <?php
            /** @var string $title */
            echo $title;
            ?>
        </p>
        <?php
            if (isset($userId) && $userId > 0) {
                echo "UserId of new user: $userId<br />Command: ";
                echo "<pre>rsync -ravz &lt;document&gt; invest@nbf01.opsserver.ch:assets/$userId/</pre>";
            }
        ?>
    </div>
</div>
</body>
</html>