<!DOCTYPE html>
<html class="helio" lang="en">
<?php \Helio\Invest\Helper\ViewHelper::includeShared('head'); ?>
<body>
<div id="notificationContainer"></div>
<div class="business-hero">
    <div class="container">
        <?php

        use Helio\Invest\Model\User;

        /** @var array $files */
        /** @var User $user */
        /** @var bool $isGuest */
        /** @var string $guestLink */
        $labelsForFiles = [
            'Milestones.pdf' => 'Financing Milestones',
            'Strategy.pdf' => 'Strategy Paper',
            'Helio_two_pager.pdf' => 'Helio on One Page and Process Map',
            'Helio_pitch_deck.pdf' => 'Helio Investors Pitch Deck',
            'Shareholder_Agreement.pdf' => 'Active Shareholder Agreement, Oct 1st 2019',
            'Financial_plan.pdf' => 'Financial Plan',
            'Factsheet_convertible_notes_seed1.pdf' => 'Factsheet: Convertible Loans Seed 1',
            'Factsheet_convertible_notes_seed2.pdf' => 'Factsheet: Convertible Loans Seed 2',
            'Factsheet_convertible_notes.pdf' => 'Factsheet: Convertible Loans',
            'Helio_Convertible.pdf' => 'Convertible Loans Contract',
            'Helio_Convertible_Seed_1.pdf' => 'Convertible Loans Contract Seed 1',
            'Helio_Convertible_Seed_2.pdf' => 'Convertible Loans Contract Seed 2',
            'Signed_Convertible.pdf' => 'Scan of signed Convertible Contract',
            'Signed_Convertible_Seed_1.pdf' => 'Scan of signed Convertible Contract Seed 1',
            'Signed_Convertible_Seed_2.pdf' => 'Scan of signed Convertible Contract Seed 2'
        ];

        ?>


        <div class="row">
            <div class="col text-center">
                <iframe src="https://player.vimeo.com/video/330772125" width="960" height="540" frameborder="0"
                        allow="autoplay; fullscreen" allowfullscreen></iframe>
            </div>
        </div>

        <br/><br/>

        <div class="row">
            <div class="col-lg-6">
                <h2>General documents</h2>
                <?php
                if (!$isGuest) {
                    echo '<div class="alert alert-warning" role="alert"><strong>You can share</strong> these documents with <a href="' . $guestLink . '">this link</a>.</div>';
                }
                ?>
                <ul class="list-group">
                    <?php
                    foreach ($files as $file) {
                        echo '<li class="list-group-item"><a target="_blank" rel="Download ' . $file . '" href="/app/get/file/' . $file . '">' . (array_key_exists($file, $labelsForFiles) ? $labelsForFiles[$file] : $file) . '</a></li>';
                    }
                    ?>
                </ul>
            </div>
            <div class="col-lg-6">
                <h2>Your personal documents</h2>

                <?php
                if ($isGuest) {
                    echo '<div class="alert alert-warning" role="alert"><strong>Please</strong> <a href="mailto:team@helio.exchange">let us know</a> if you want to register.</div>';

                } else {

                    echo '<div class="alert alert-warning" role="alert"><strong>Please don\'t share</strong> these documents.</div>';

                    echo '<ul class="list-group">';
                    foreach ($user->getFiles() as $file) {
                        echo '<li class="list-group-item"><a target="_blank" rel="Download ' . $file . '" href="/app/get/file/personal/' . $file . '">' . (array_key_exists($file, $labelsForFiles) ? $labelsForFiles[$file] : $file) . '</a></li>';
                    }
                    echo '</ul>';
                }
                ?>
            </div>
        </div>
        <br/><br/>
    </div>
</div>
</body>
</html>
