<?php

use Helio\Invest\Model\User;

/** @var array $files */
/** @var User $user */
$labelsForFiles = [
    'Milestones.pdf' => 'Financing Milestones',
    'Strategy.pdf' => 'Strategy Paper',
    'Helio_two_pager.pdf' => 'Helio on One Page and Process Map',
    'Helio_pitch_deck.pdf' => 'Helio Investors\' Pitch Deck',
    'Financial_plan.pdf' => 'Financial Plan',
    'Helio_Convertible.pdf' => 'Convertible Loan Contract'
];

?>

<div>
    <iframe src="https://player.vimeo.com/video/330772125" width="1280" height="720" frameborder="0"
            allow="autoplay; fullscreen" allowfullscreen></iframe>
</div>
<p>
    Please don't share these documents directly, always invite people to this platform.<br/>
    We'll update the documents from time to time. You'll get notified when new versions or new documents will be
    available here.
</p>
<h2>General documents</h2>
<ul>
    <?php
    foreach ($files as $file) {
        echo '<li><a target="_blank" alt="Download ' . $file . '" href="/app/get/file/' . $file . '">' . (array_key_exists($file, $labelsForFiles) ? $labelsForFiles[$file] : $file) . '</a></li>';
    }
    ?>
</ul>
<h2>Your documents</h2>

<ul>

    <?php
    foreach ($user->getFiles() as $file) {
        echo '<li><a target="_blank" alt="Download ' . $file . '" href="/app/get/file/personal/' . $file . '">' . (array_key_exists($file, $labelsForFiles) ? $labelsForFiles[$file] : $file) . '</a></li>';
    }
    ?>
</ul>